### ISSUE TITLE
Sprint Blog (Phil)

### ISSUE THREAD

**Issue by redthre3** [FoodFightCPP/FoodFight#1]

**Comment by petersteele111** [comment]
![image](https://user-images.githubusercontent.com/20760406/104615862-a5477800-5657-11eb-8574-6a1d0bb65604.png)

**Comment by redthre3** [comment]
[https://philcit280.wordpress.com/](url)

**Comment by redthre3** [comment]
![image](https://user-images.githubusercontent.com/44672323/105636075-6c1bbe80-5e34-11eb-9781-3fe0f489d46a.png)
