### ISSUE TITLE
Create Wireframes for the App

### ISSUE THREAD

**Issue by petersteele111** [FoodFightCPP/FoodFight#14]
Create wireframes for the application and settle on a design that we all agree on

**Comment by redthre3** [comment]
https://xd.adobe.com/view/502f161b-060f-45f5-9dde-1e62cb12494d-057c/

**Comment by redthre3** [comment]
we can adjust colors, but i did some of the prototyping as well to show function of links for contacts and how it will look with pop outs

**Comment by petersteele111** [comment]
Wireframes have been created and added to the Project Notebook, closing this issue
