### ISSUE TITLE
Design and colorize Logo

### ISSUE THREAD

**Issue by petersteele111** [FoodFightCPP/FoodFight#15]
Design and colorize the logo as a vector for web use

**Comment by ChrisLehr5** [comment]
![image](https://user-images.githubusercontent.com/49166368/107126147-291e0a00-687c-11eb-8c5d-07baef52c96c.png)

**Comment by ChrisLehr5** [comment]
Personally, I like the yellow. But after my brother said it looked like an egg, I decided I better try blue too for review

**Comment by redthre3** [comment]
Can you put the different file types in a zip and distribute it? I can put them in the assets folder on the repo for the mobile app for reference as well.

**Comment by petersteele111** [comment]
This is complete, closing the issue
