### ISSUE TITLE
Setup Azure site for Backend

### ISSUE THREAD

**Issue by petersteele111** [FoodFightCPP/FoodFight#20]
Setup azure to deploy backend website and DB instance

**Comment by redthre3** [comment]
[https://foodfight.azurewebsites.net](url)

**Comment by redthre3** [comment]
[https://foodfight.azurewebsites.net](url)

**Comment by redthre3** [comment]
![image](https://user-images.githubusercontent.com/44672323/105067729-01424000-5a4e-11eb-8552-39cb9891e82d.png)

**Comment by redthre3** [comment]
I created a new repo on here for the web app to run continuous updates through GitHub. Just need Authorization from @petersteele111 for access for Azure. I will point the Azure deployment to the repo.

**Comment by petersteele111** [comment]
Its been approved and ready to go
