### ISSUE TITLE
Digital Notebook

### ISSUE THREAD

**Issue by redthre3** [FoodFightCPP/FoodFight#4]

**Comment by redthre3** [comment]
[https://docs.google.com/document/d/1Ma3QQiibdUyfABTXAaURtwdmZ1Xmgg2bbTaa_6rG8Mk/edit](url)

**Comment by petersteele111** [comment]
Thanks! I will make sure to bookmark it :)

**Comment by redthre3** [comment]
![image](https://user-images.githubusercontent.com/44672323/105636166-01b74e00-5e35-11eb-8a42-73a1132a1713.png)
