### ISSUE TITLE
Create FoodFight Functionality/Flow Diagram 

### ISSUE THREAD

**Issue by redthre3** [FoodFightCPP/FoodFight#48]

**Comment by petersteele111** [comment]
Do we have the flow diagram posted so that we can move this to complete and close this issue out?

**Comment by ChrisLehr5** [comment]
This is in review pending the presentation John said we would have, in case changes need to be made. 
If no presentation occurs, will move into closed at sprint end.

**Comment by petersteele111** [comment]
YAY

**Comment by redthre3** [comment]
Its in the project notebook
