### ISSUE TITLE
Role assignments

### ISSUE THREAD

**Issue by redthre3** [FoodFightCPP/FoodFight#5]

**Comment by petersteele111** [comment]
Well I am working on the mobile app, Phil you are doing the admin site to manage everything, and Christine is handling the front facing marketing/information website. As far as specific roles with titles go though, we would need to discuss those and what they entail as far as this project goes for duties. That is something we can discuss shortly though.

**Comment by petersteele111** [comment]
Peter - Application Dev/Scrum Master
Phil - Admin/Backend Dev
Christine - Front End/Backend Dev
