### ISSUE TITLE
Sprint 3 Presentation

### ISSUE THREAD

**Issue by ChrisLehr5** [FoodFightCPP/FoodFight#74]
ETC 3/15/21

https://docs.google.com/presentation/d/1wG28j66_gXcsIGH93VqGO8NgU0Wl-1O35HUyjSivvJ0/edit#slide=id.gcb9a0b074_1_0

**Comment by petersteele111** [comment]
I would say that this is complete. We added in everything that we needed and discussed it all while running through it.
